apiVersion: v1
kind: Pod
metadata:
  name: intel-dpdk-pod
  namespace: openshift-sriov-network-operator
  annotations:
    k8s.v1.cni.cncf.io/networks: dpdk-network1
spec:
  nodeSelector:
    kubernetes.io/hostname: worker1.dsp.lab
  containers:
  - name: example-pod
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: registry.redhat.io/rhel7/rhel-tools 
    ports: 
    - containerPort: 80
