apiVersion: v1
kind: Pod
metadata:
  name: sriov-pod-2
  namespace: testns
  annotations:
    k8s.v1.cni.cncf.io/networks: worker1.dsp.lab-sriov-network
spec:
  nodeSelector:
    kubernetes.io/hostname: worker2.dsp.lab
  containers:
  - name: example-pod1
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: registry.redhat.io/rhel7/rhel-tools 
    ports: 
    - containerPort: 80

