apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: worker2-network
  namespace: openshift-sriov-network-operator
spec:
  resourceName: compute_1_net_devices
  networkNamespace: testns
  ipam: '{"type":"static","addresses": [{"address":"192.168.150.53/24", "gateway":"192.168.150.1"}],"routes": [{"dst":"192.168.50.0/24","gw":"192.168.150.1"}]}'
  capabilities: '{"mac": true, "ips": true}'
